<?php

namespace Bagene\PhPayments\Xendit\Models;

use Bagene\PhPayments\Requests\BaseResponse;
use Bagene\PhPayments\Requests\Request;

class XenditCreateInvoiceRequest extends Request implements XenditRequestInterface
{
    public function setDefaults(): void
    {
        $this->defaults = [
            'payment_methods' => config('payments.xendit.payment_methods')
                ?? $args['payment_methods'] ?? [],
            'currency' => config('payments.xendit.default_currency')
                ?? $args['default_currency'] ?? ''
        ];
        $this->body = array_merge($this->defaults, $this->body);
    }

    public function getEndpoint(): string
    {
        $host = static::PRODUCTION_BASE_URL;
        if (config('payments.xendit.use_sandbox')) {
            $host = static::SANDBOX_BASE_URL;
        }

        return $host . static::INVOICE_ENDPOINT;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function send(): XenditInvoiceResponse
    {
        // TODO: Validate the request body

        $response = parent::sendRequest(); // TODO: Change the autogenerated stub

        return new XenditInvoiceResponse($response);
    }
}
